import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header'



export const metadata: Metadata = {
  title: "JB's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <Header />
      </header>
      <body>
        {children}
      </body>
      <footer>
        
      </footer>
    </html>
  );
}
